In [2]:
import pandas as pd

In [3]:
#Read File Egresos Hospitalarios
egresos_hospitalarios_path = 'C:/Users/Nancy/Documents/Data Boot Camp/Proyecto/2016_Sectorial.csv'
egresos = pd.read_csv(egresos_hospitalarios_path)

In [7]:
egresos.head()

,DH,CEDOCVE,CLUES,MOTEGRE,SEXO,EDAD,EDAD1,DIAS_ESTA,AFECPRIN4,CAUSABAS4
0,1,3,BSSSA001213,2,2,4,52,1,R13X,8888
1,1,3,BSSSA001213,2,2,3,44,0,K011,8888
2,1,3,BSSSA001213,1,2,3,31,1,O994,8888
3,1,3,BSSSA001213,2,2,3,36,4,K801,8888
4,1,3,BSSSA001213,2,2,1,4,0,T183,8888

In [5]:
egresos.count()

DH           5608991
CEDOCVE      5608991
CLUES        5608991
MOTEGRE      5608991
SEXO         5608991
EDAD         5608991
EDAD1        5608991
DIAS_ESTA    5608991
AFECPRIN4    5608991
CAUSABAS4    5608991
dtype: int64

In [6]:
catalogo_hospitales_path = 'C:/Users/Nancy/Documents/Data Boot Camp/Proyecto/ESTABLECIMIENTO_SALUD_201902.csv'
catalogo_hospitales = pd.read_csv(catalogo_hospitales_path,encoding="latin1")

C:\Users\Nancy\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (59,60) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [47]:
#Filtrar enfermedades
egresos.loc[egresos['AFECPRIN4']=='J45'].head()

Empty DataFrame
Columns: [DH, CEDOCVE, CLUES, MOTEGRE, SEXO, EDAD, EDAD1, DIAS_ESTA, AFECPRIN4, CAUSABAS4]
Index: []

In [13]:
#Filro por enfermedades respiratorias - empiezan con J
egresosj = egresos.loc[egresos["AFECPRIN4"].str.startswith("J")==True]
egresosj.head()

,DH,CEDOCVE,CLUES,MOTEGRE,SEXO,EDAD,EDAD1,DIAS_ESTA,AFECPRIN4,CAUSABAS4
61,1,3,BSSSA001213,2,1,5,86,8,J449,8888
71,1,15,MCSSA007982,2,2,3,44,7,J459,8888
119,1,15,MCSSA008233,2,1,5,84,6,J189,8888
127,1,3,BSSSA001213,2,1,4,64,2,J189,8888
151,1,3,BSSSA001213,2,1,4,60,13,J159,8888

In [12]:
#Filro por enfermedades respiratorias - empiezan con J de CDMX
#egresosjcdmx=egresos[(egresos['AFECPRIN4'].str.startswith("J")==True) & (egresos['CEDOCVE']=='3')]
#males = df[(df[Gender]=='Male') & (df[Year]==2014)]

egresosjcdmx=egresosj.loc[egresosj['CEDOCVE']=='3']

egresosjcdmx.head()

NameError: name 'egresosj' is not defined

In [53]:
egresosj.count()

DH           266708
CEDOCVE      266708
CLUES        266708
MOTEGRE      266708
SEXO         266708
EDAD         266708
EDAD1        266708
DIAS_ESTA    266708
AFECPRIN4    266708
CAUSABAS4    266708
dtype: int64

In [8]:
catalogo_hospitales.head()

,CLUES,NOMBRE DE LA ENTIDAD,CLAVE DE LA ENTIDAD,NOMBRE DEL MUNICIPIO,CLAVE DEL MUNICIPIO,NOMBRE DE LA LOCALIDAD,CLAVE DE LA LOCALIDAD,NOMBRE DE LA JURISDICCION,CLAVE DE LA JURISDICCION,NOMBRE DE LA INSTITUCION,...,CLAVE ESTRATO UNIDAD,TIPO OBRA,CLAVE TIPO OBRA,HORARIO DE ATENCION,AREAS Y SERVICIOS,ULTIMO MOVIMIENTO,FECHA ULTIMO MOVIMIENTO,CERTIFICACION CSG,TIPO CERTIFICACION,VIGENCIA CERTIFICACION
0,ASDIF000011,AGUASCALIENTES,1,AGUASCALIENTES,1,AGUASCALIENTES,1,AGUASCALIENTES,1,SISTEMA NACIONAL PARA EL DESARROLLO INTEGRAL D...,...,2,NO ESPECIFICADO,6.0,NaN,NaN,CAMBIO,2012-01-03,NO CERTIFICADO,NO ESPECIFICADO,NaN
1,ASDIF000023,AGUASCALIENTES,1,COSÍO,4,COSIO,1,RINCÓN DE ROMOS,2,SISTEMA NACIONAL PARA EL DESARROLLO INTEGRAL D...,...,2,NO ESPECIFICADO,6.0,NaN,NaN,CAMBIO,2012-01-03,NO CERTIFICADO,NO ESPECIFICADO,NaN
2,ASDIF000035,AGUASCALIENTES,1,RINCÓN DE ROMOS,7,RINCON DE ROMOS,1,RINCÓN DE ROMOS,2,SISTEMA NACIONAL PARA EL DESARROLLO INTEGRAL D...,...,2,NO ESPECIFICADO,6.0,NaN,NaN,CAMBIO,2012-01-03,NO CERTIFICADO,NO ESPECIFICADO,NaN
3,ASDIF000040,AGUASCALIENTES,1,TEPEZALÁ,9,TEPEZALA,1,RINCÓN DE ROMOS,2,SISTEMA NACIONAL PARA EL DESARROLLO INTEGRAL D...,...,2,NO ESPECIFICADO,6.0,NaN,NaN,CAMBIO,2012-01-03,NO CERTIFICADO,NO ESPECIFICADO,NaN
4,ASDIF000052,AGUASCALIENTES,1,CALVILLO,3,CALVILLO,1,CALVILLO,3,SISTEMA NACIONAL PARA EL DESARROLLO INTEGRAL D...,...,2,NO ESPECIFICADO,6.0,NaN,NaN,CAMBIO,2012-01-03,NO CERTIFICADO,NO ESPECIFICADO,NaN

In [11]:
catalogo_hospitales.count()

CLUES                            39175
NOMBRE DE LA ENTIDAD             39175
CLAVE DE LA ENTIDAD              39175
NOMBRE DEL MUNICIPIO             39175
CLAVE DEL MUNICIPIO              39175
NOMBRE DE LA LOCALIDAD           39175
CLAVE DE LA LOCALIDAD            39175
NOMBRE DE LA JURISDICCION        39175
CLAVE DE LA JURISDICCION         39175
NOMBRE DE LA INSTITUCION         39175
CLAVE DE LA INSTITUCION          39175
CLAVE CORTA DE LA INSTITUCION    39175
NOMBRE TIPO ESTABLECIMIENTO      39175
CLAVE TIPO ESTABLECIMIENTO       39175
NOMBRE DE TIPOLOGIA              39175
CLAVE DE TIPOLOGIA               39173
NOMBRE DE SUBTIPOLOGIA           39175
CLAVE DE SUBTIPOLOGIA            39173
CLAVE SCIAN                       3126
DESCRIPCION CLAVE SCIAN           3126
CONSULTORIOS DE MED GRAL         39175
CONSULTORIOS EN OTRAS AREAS      39175
TOTAL DE CONSULTORIOS            39175
CAMAS EN AREA DE HOS             39175
CAMAS EN OTRAS AREAS             39175
TOTAL DE CAMAS                   39175
NOMBRE DE LA UNIDAD              39175
CLAVE DE VIALIDAD                14962
TIPO DE VIALIDAD                 14962
VIALIDAD                         39061
                                 ...
UNIDAD MOVIL MARCA                2770
UNIDAD MOVIL MODELO               2767
UNIDAD MOVIL CAPACIDAD            2769
UNIDAD MOVIL PROGRAMA             2861
UNIDAD MOVIL CLAVE PROGRAMA       2861
UNIDAD MOVIL TIPO                 2861
UNIDAD MOVIL CLAVE TIPO           2861
UNIDAD MOVIL TIPOLOGIA            2861
UNIDAD MOVIL CLAVE TIPOLOGIA      2861
LONGITUD                         38093
LATITUD                          38093
NOMBRE DE LA INS ADM             39166
CLAVE DE LA INS ADM              39166
NIVEL ATENCION                   39175
CLAVE NIVEL ATENCION             39175
ESTATUS ACREDITACION             39175
CLAVE ESTATUS ACREDITACION       39175
ACREDITACIONES                    7915
SUBACREDITACION                   7915
ESTRATO UNIDAD                   39175
CLAVE ESTRATO UNIDAD             39175
TIPO OBRA                        38868
CLAVE TIPO OBRA                  38868
HORARIO DE ATENCION               9983
AREAS Y SERVICIOS                 7585
ULTIMO MOVIMIENTO                39175
FECHA ULTIMO MOVIMIENTO          39175
CERTIFICACION CSG                37754
TIPO CERTIFICACION               37754
VIGENCIA CERTIFICACION             228
Length: 80, dtype: int64

In [13]:
catalogo_hospitales['NOMBRE DE LA ENTIDAD'].unique()

array(['AGUASCALIENTES', 'BAJA CALIFORNIA', 'BAJA CALIFORNIA SUR',
       'CAMPECHE', 'CHIHUAHUA', 'COAHUILA DE ZARAGOZA', 'COLIMA',
       'CHIAPAS', 'CIUDAD DE MEXICO', 'DURANGO', 'GUERRERO', 'GUANAJUATO',
       'HIDALGO', 'JALISCO', 'MEXICO', 'MICHOACAN DE OCAMPO', 'MORELOS',
       'NUEVO LEON', 'NAYARIT', 'OAXACA', 'PUEBLA', 'QUINTANA ROO',
       'QUERETARO', 'SINALOA', 'SAN LUIS POTOSI', 'SONORA', 'TABASCO',
       'TLAXCALA', 'TAMAULIPAS', 'VERACRUZ DE IGNACIO DE LA LLAVE',
       'YUCATAN', 'ZACATECAS'], dtype=object)

In [14]:
hospitales_cdmx = catalogo_hospitales.loc[catalogo_hospitales['NOMBRE DE LA ENTIDAD']=='CIUDAD DE MEXICO']
hospitales_cdmx.head()

,CLUES,NOMBRE DE LA ENTIDAD,CLAVE DE LA ENTIDAD,NOMBRE DEL MUNICIPIO,CLAVE DEL MUNICIPIO,NOMBRE DE LA LOCALIDAD,CLAVE DE LA LOCALIDAD,NOMBRE DE LA JURISDICCION,CLAVE DE LA JURISDICCION,NOMBRE DE LA INSTITUCION,...,CLAVE ESTRATO UNIDAD,TIPO OBRA,CLAVE TIPO OBRA,HORARIO DE ATENCION,AREAS Y SERVICIOS,ULTIMO MOVIMIENTO,FECHA ULTIMO MOVIMIENTO,CERTIFICACION CSG,TIPO CERTIFICACION,VIGENCIA CERTIFICACION
6439,DFCIJ000011,CIUDAD DE MEXICO,9,VENUSTIANO CARRANZA,17,VENUSTIANO CARRANZA,1,VENUSTIANO CARRANZA,16,CENTROS DE INTEGRACION JUVENIL,...,2,NO ESPECIFICADO,6.0,"CONSULTA EXTERNA - L,M,X,J,V, DE 08:00:00 A 20...",NaN,ALTA,2018-10-16,NO CERTIFICADO,NO ESPECIFICADO,NaN
6440,DFCIJ000023,CIUDAD DE MEXICO,9,CUAUHTÉMOC,15,NO ESPECIFICADO,9999,CUAUHTÉMOC,15,CENTROS DE INTEGRACION JUVENIL,...,2,NO ESPECIFICADO,6.0,"CONSULTA EXTERNA - L,M,X,J,V, DE 08:00:00 A 19...",NaN,ALTA,2018-10-16,NO CERTIFICADO,NO ESPECIFICADO,NaN
6441,DFCIJ000035,CIUDAD DE MEXICO,9,CUAJIMALPA DE MORELOS,4,CUAJIMALPA DE MORELOS,1,CUAJIMALPA,7,CENTROS DE INTEGRACION JUVENIL,...,2,NO ESPECIFICADO,6.0,"CONSULTA EXTERNA - L,M,X,J,V, DE 08:00:00 A 16...",NaN,ALTA,2018-10-16,NO CERTIFICADO,NO ESPECIFICADO,NaN
6442,DFCIJ000040,CIUDAD DE MEXICO,9,COYOACÁN,3,COYOACAN,1,COYOACÁN,4,CENTROS DE INTEGRACION JUVENIL,...,2,NO ESPECIFICADO,6.0,"CONSULTA EXTERNA - L,M,X,J,V, DE 08:00:00 A 20...",NaN,ALTA,2018-10-16,NO CERTIFICADO,NO ESPECIFICADO,NaN
6443,DFCIJ000052,CIUDAD DE MEXICO,9,BENITO JUÁREZ,14,BENITO JUAREZ,1,BENITO JUÁREZ,14,CENTROS DE INTEGRACION JUVENIL,...,2,NO ESPECIFICADO,6.0,"CONSULTA EXTERNA - L,M,X,J,V, DE 08:00:00 A 19...",NaN,ALTA,2018-10-16,NO CERTIFICADO,NO ESPECIFICADO,NaN

hospitales_cdmx.count()

In [43]:
hospitales_cdmx.loc[hospitales_cdmx['CLUES']=='ASDIF000011'].head()

Empty DataFrame
Columns: [CLUES, NOMBRE DE LA ENTIDAD, CLAVE DE LA ENTIDAD, NOMBRE DEL MUNICIPIO, CLAVE DEL MUNICIPIO, NOMBRE DE LA LOCALIDAD, CLAVE DE LA LOCALIDAD, NOMBRE DE LA JURISDICCION, CLAVE DE LA JURISDICCION, NOMBRE DE LA INSTITUCION, CLAVE DE LA INSTITUCION, CLAVE CORTA DE LA INSTITUCION, NOMBRE TIPO ESTABLECIMIENTO, CLAVE TIPO ESTABLECIMIENTO, NOMBRE DE TIPOLOGIA, CLAVE DE TIPOLOGIA, NOMBRE DE SUBTIPOLOGIA, CLAVE DE SUBTIPOLOGIA, CLAVE SCIAN, DESCRIPCION CLAVE SCIAN, CONSULTORIOS DE MED GRAL, CONSULTORIOS EN OTRAS AREAS, TOTAL DE CONSULTORIOS, CAMAS EN AREA DE HOS, CAMAS EN OTRAS AREAS, TOTAL DE CAMAS, NOMBRE DE LA UNIDAD, CLAVE DE VIALIDAD, TIPO DE VIALIDAD, VIALIDAD, NUMERO EXTERIOR, NUMERO INTERIOR, CLAVE DEL TIPO DE ASENTAMIENTO, TIPO DE ASENTAMIENTO, ASENTAMIENTO, ENTRE TIPO DE VIALIDAD 1, ENTRE VIALIDAD 1, ENTRE TIPO DE VIALIDAD 2, ENTRE VIALIDAD 2, OBSERVACIONES DE LA DIRECCION, CODIGO POSTAL, ESTATUS DE OPERACION, CLAVE DE ESTATUS DE OPERACION, TIENE LICENCIA SANITARIA, NUMERO DE LICENCIA SANITARIA, TIENE AVISO DE FUNCIONAMIENTO, FECHA EMISION AV. FUN., RFC DEL ESTABLECIMIENTO, FECHA DE CONSTRUCCION, FECHA DE INICIO DE OPERACION, UNIDAD MOVIL MARCA, UNIDAD MOVIL MODELO, UNIDAD MOVIL CAPACIDAD, UNIDAD MOVIL PROGRAMA, UNIDAD MOVIL CLAVE PROGRAMA, UNIDAD MOVIL TIPO, UNIDAD MOVIL CLAVE TIPO, UNIDAD MOVIL TIPOLOGIA, UNIDAD MOVIL CLAVE TIPOLOGIA, LONGITUD, LATITUD, NOMBRE DE LA INS ADM, CLAVE DE LA INS ADM, NIVEL ATENCION, CLAVE NIVEL ATENCION, ESTATUS ACREDITACION, CLAVE ESTATUS ACREDITACION, ACREDITACIONES, SUBACREDITACION, ESTRATO UNIDAD, CLAVE ESTRATO UNIDAD, TIPO OBRA, CLAVE TIPO OBRA, HORARIO DE ATENCION, AREAS Y SERVICIOS, ULTIMO MOVIMIENTO, FECHA ULTIMO MOVIMIENTO, CERTIFICACION CSG, TIPO CERTIFICACION, VIGENCIA CERTIFICACION]
Index: []

[0 rows x 80 columns]

In [39]:
#Merge egresos-cdmx vs. catalogo hospitales
egresos2 = pd.merge(egresos,hospitales_cdmx[['CLUES','NOMBRE DE LA ENTIDAD']],on='CLUES',how='left')

#df = pd.merge(df,df2[['Key_Column','Target_Column']],on='Key_Column', how='left')
egresos2.head(100)

,DH,CEDOCVE,CLUES,MOTEGRE,SEXO,EDAD,EDAD1,DIAS_ESTA,AFECPRIN4,CAUSABAS4,NOMBRE DE LA ENTIDAD
0,1,3,BSSSA001213,2,2,4,52,1,R13X,8888,NaN
1,1,3,BSSSA001213,2,2,3,44,0,K011,8888,NaN
2,1,3,BSSSA001213,1,2,3,31,1,O994,8888,NaN
3,1,3,BSSSA001213,2,2,3,36,4,K801,8888,NaN
4,1,3,BSSSA001213,2,2,1,4,0,T183,8888,NaN
5,1,3,BSSSA001213,2,2,1,3,1,N049,8888,NaN
6,1,3,BSSSA001213,2,2,4,58,7,E115,8888,NaN
7,1,3,BSSSA001213,2,2,3,17,6,O159,8888,NaN
8,1,3,BSSSA001213,2,2,3,19,1,K801,8888,NaN
9,1,3,BSSSA001213,1,2,3,19,1,O339,8888,NaN
10,1,3,BSSSA001213,1,2,3,27,1,O809,8888,NaN
11,1,3,BSSSA001213,1,2,3,18,1,O809,8888,NaN
12,1,3,BSSSA001213,2,2,3,37,0,Z470,8888,NaN
13,1,3,BSSSA001213,2,2,3,35,0,K011,8888,NaN
14,1,3,BSSSA001213,2,2,3,43,3,N884,8888,NaN
15,1,3,BSSSA001213,2,1,1,3,3,M796,8888,NaN
16,1,3,BSSSA001213,2,2,5,65,14,E115,8888,NaN
17,1,3,BSSSA001213,2,2,4,63,0,D171,8888,NaN
18,1,3,BSSSA001213,2,2,4,60,2,I872,8888,NaN
19,1,3,BSSSA001213,2,1,3,22,0,K011,8888,NaN
20,1,3,BSSSA001213,2,1,2,5,6,Z512,8888,NaN
21,1,3,BSSSA001213,1,2,3,40,1,O339,8888,NaN
22,1,3,BSSSA001213,2,1,5,67,9,K297,8888,NaN
23,1,3,BSSSA001213,1,2,3,15,1,O809,8888,NaN
24,1,3,BSSSA001213,2,2,3,35,1,K20X,8888,NaN
25,1,3,BSSSA001213,2,2,5,84,2,I259,8888,NaN
26,1,3,BSSSA001213,2,2,4,56,3,C539,8888,NaN
27,1,3,BSSSA001213,2,2,3,19,2,N189,8888,NaN
28,1,3,BSSSA001213,2,1,3,28,7,F155,8888,NaN
29,1,3,BSSSA001213,2,2,3,42,0,D171,8888,NaN
...,...,...,...,...,...,...,...,...,...,...,...
70,1,15,MCSSA007982,2,2,5,66,0,N189,8888,NaN
71,1,15,MCSSA007982,2,2,3,44,7,J459,8888,NaN
72,1,15,MCSSA007982,2,2,2,7,1,K429,8888,NaN
73,1,15,MCSSA007982,2,2,3,26,1,O809,8888,NaN
74,1,15,MCSSA007982,2,2,3,18,1,O809,8888,NaN
75,1,15,MCSSA007982,2,1,3,44,0,N189,8888,NaN
76,1,15,MCSSA007982,2,2,3,26,0,N189,8888,NaN
77,1,15,MCSSA007982,2,2,3,22,0,N189,8888,NaN
78,1,15,MCSSA007982,2,2,3,42,0,N189,8888,NaN
79,1,15,MCSSA007982,2,1,3,38,0,N189,8888,NaN
80,1,15,MCSSA007982,2,1,3,34,0,N189,8888,NaN
81,1,15,MCSSA007982,2,1,5,67,0,N189,8888,NaN
82,1,15,MCSSA007982,2,1,3,22,0,N189,8888,NaN
83,1,15,MCSSA007982,2,2,3,35,0,N189,8888,NaN
84,1,15,MCSSA007982,2,1,3,22,0,N189,8888,NaN
85,1,15,MCSSA007982,2,1,4,57,0,N189,8888,NaN
86,1,15,MCSSA007982,2,1,5,66,0,N189,8888,NaN
87,1,15,MCSSA007982,2,1,3,38,0,N189,8888,NaN
88,1,15,MCSSA007982,2,2,3,41,0,N189,8888,NaN
89,1,15,MCSSA007982,2,1,3,25,0,N189,8888,NaN
90,1,15,MCSSA007982,2,2,4,55,0,N189,8888,NaN
91,1,15,MCSSA007982,2,2,4,46,0,N189,8888,NaN
92,1,15,MCSSA007982,2,2,3,36,0,N189,8888,NaN
93,1,15,MCSSA007982,2,1,3,36,0,N189,8888,NaN
94,1,15,MCSSA007982,2,1,3,22,0,N189,8888,NaN
95,1,15,MCSSA007982,2,1,3,33,0,N189,8888,NaN
96,1,15,MCSSA007982,2,1,4,52,0,N189,8888,NaN
97,1,15,MCSSA007982,2,2,3,26,0,N189,8888,NaN
98,1,15,MCSSA007982,2,1,3,19,0,N189,8888,NaN
99,1,15,MCSSA007982,2,1,3,26,0,N189,8888,NaN

In [ ]:
#Merge egresos-cdmx vs. catalogo hospitales con clave de la entidad
egresos2 = pd.merge(egresos,hospitales_cdmx[['CLAVE D','NOMBRE DE LA ENTIDAD']],on='CLUES',how='left')

#df = pd.merge(df,df2[['Key_Column','Target_Column']],on='Key_Column', how='left')
egresos2.head(100)

In [40]:
egresos2['NOMBRE DE LA ENTIDAD'].nunique()

1